APP_OPTIM := release
APP_PLATFORM := android-9
APP_STL := c++_static
APP_CPPFLAGS += -frtti
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -DANDROID
APP_ABI := armeabi armeabi-v7a x86
APP_MODULES := ssl crypto curl
NDK_TOOLCHAIN_VERSION := clang
